# making a model that adds any Two Numbers from -10 to 10 
## Author: Mario George
### which can be changed to any two numbers from the boundaries of the torch.randint method

In [3]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import scipy.stats as stats
import sklearn.metrics as skm
from torch.utils.data import DataLoader,TensorDataset
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg')

In [4]:
N=20000
data=torch.randint(-10,11,size=(N,2)).float()


In [5]:
labels=torch.sum(data,dim=1,keepdim=True)
labels

tensor([[ -7.],
        [ -2.],
        [-11.],
        ...,
        [-19.],
        [ 16.],
        [-10.]])

In [6]:
# for i in range(len(labels)):
#     print(f'{data[i]},{labels[i]}')
for i in range(5):
    print(f'{data[i]},{labels[i]}')

tensor([-5., -2.]),tensor([-7.])
tensor([ 5., -7.]),tensor([-2.])
tensor([-9., -2.]),tensor([-11.])
tensor([ 1., 10.]),tensor([11.])
tensor([9., 5.]),tensor([14.])


In [7]:
train_dataset=TensorDataset(data,labels)
batchNumber=16
train_loader=DataLoader(train_dataset,shuffle=True,drop_last=True,batch_size=batchNumber)


In [8]:
def createModal():

    class Net(nn.Module) :
        def __init__(self):
            super().__init__()
            self.input=nn.Linear(2,16)
            self.hidden=nn.Linear(16,16)
            self.output=nn.Linear(16,1)
        def forward(self,x):
            x=F.relu(self.input(x))
            x=F.relu(self.hidden(x))
            return self.output(x)
    net=Net()
    lossFunction=nn.MSELoss()
    optimizer=torch.optim.Adam(net.parameters(),lr=.001)
    return net,lossFunction,optimizer


In [9]:
def TrainModal():
    numEpochs=100
    net,lossFunction,optimizer=createModal()
    losses=[]

    for i in range(numEpochs):
        batchLoss=[]
        batchAcc=[]
        for X,y in train_loader:
            yHat=net(X)
      
            loss=lossFunction(yHat,y)
            batchLoss.append(loss.item())

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        
    with torch.no_grad():
        yHat=net(data)
        acc=100*torch.mean((np.abs(yHat-labels)<1).float())
    with torch.no_grad():
        # test using newly generated numbers and the sum 
        newDataTest=torch.randint(-10,11,size=(N,2)).float()
        newLabelsTest=torch.sum(newDataTest,dim=1,keepdim=True)
        yHat=net(newDataTest)
        testAcc=100*torch.mean((np.abs(yHat-newLabelsTest)<1).float())
    

    return losses,acc,testAcc,net

        
losses,acc,testAcc,net=TrainModal()
print(acc)
print(testAcc)

tensor(100.)
tensor(100.)


In [21]:
import time
for i in range(10):
    currentTime=time.process_time()
    _,acc,testAcc,_2=TrainModal()
    # i used _ because i won't be using the losses
    print(f'#{i} the train acc is {acc} and test acc is {testAcc} it took {time.process_time()-currentTime} to complete')


#0 the train acc is 100.0 and test acc is 100.0 it took 146.01827689899994 to complete
#1 the train acc is 100.0 and test acc is 100.0 it took 144.24295877600002 to complete
#2 the train acc is 100.0 and test acc is 100.0 it took 148.17667183699996 to complete
#3 the train acc is 100.0 and test acc is 100.0 it took 161.59789799700002 to complete
#4 the train acc is 100.0 and test acc is 100.0 it took 145.27511830799995 to complete
#5 the train acc is 100.0 and test acc is 100.0 it took 146.0603996499999 to complete
#6 the train acc is 100.0 and test acc is 100.0 it took 150.60515977599994 to complete
#7 the train acc is 100.0 and test acc is 100.0 it took 141.30256485899986 to complete
#8 the train acc is 100.0 and test acc is 100.0 it took 145.19126052600018 to complete
#9 the train acc is 100.0 and test acc is 100.0 it took 145.77639754600023 to complete


In [10]:
losses,acc,testAcc,net=TrainModal()

yHat=net(data)
# use len(labels) for all the data i will print the first 50 predict/actual output
for i in range(50):
    
    print(f'{yHat[i].item()},{labels[i].item()}')

-7.002230644226074,-7.0
-2.000800371170044,-2.0
-11.003644943237305,-11.0
11.002310752868652,11.0
14.002938270568848,14.0
3.000311851501465,3.0
5.000998497009277,5.0
13.00274658203125,13.0
-11.003644943237305,-11.0
-2.0062127113342285,-2.0
6.001201629638672,6.0
-1.0002928972244263,-1.0
-12.004645347595215,-12.0
3.000096321105957,3.0
-2.000985860824585,-2.0
11.002310752868652,11.0
-5.001738548278809,-5.0
6.999540328979492,7.0
-6.001956939697266,-6.0
1.993873953819275,2.0
-2.000800371170044,-2.0
-3.9997284412384033,-4.0
3.996981620788574,4.0
-16.00584602355957,-16.0
-11.003644943237305,-11.0
8.001654624938965,8.0
1.9989615678787231,2.0
10.002091407775879,10.0
-16.00584602355957,-16.0
-5.0060834884643555,-5.0
11.00226879119873,11.0
-3.001554489135742,-3.0
1.0015884637832642,1.0
-4.9999237060546875,-5.0
4.99758768081665,5.0
0.9998081922531128,1.0
-18.00687599182129,-18.0
2.6054680347442627e-05,0.0
-9.002817153930664,-9.0
-12.004321098327637,-12.0
5.000635147094727,5.0
-1.0004175901412964,-