# making a model that adds any Two Numbers from -10 to 10 
## Author: Mario George
### which can be changed to any two numbers from the boundaries of the torch.randint method

In [3]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import scipy.stats as stats
import sklearn.metrics as skm
from torch.utils.data import DataLoader,TensorDataset
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib_inline
matplotlib_inline.backend_inline.set_matplotlib_formats('svg')

In [4]:
N=20000
data=torch.randint(-10,11,size=(N,2)).float()


In [5]:
labels=torch.sum(data,dim=1,keepdim=True)
labels

tensor([[ -7.],
        [ -2.],
        [-11.],
        ...,
        [-19.],
        [ 16.],
        [-10.]])

In [6]:
# for i in range(len(labels)):
#     print(f'{data[i]},{labels[i]}')
for i in range(5):
    print(f'{data[i]},{labels[i]}')

tensor([-5., -2.]),tensor([-7.])
tensor([ 5., -7.]),tensor([-2.])
tensor([-9., -2.]),tensor([-11.])
tensor([ 1., 10.]),tensor([11.])
tensor([9., 5.]),tensor([14.])


In [17]:
train_dataset=TensorDataset(data,labels)
batchNumber=16
train_loader=DataLoader(train_dataset,shuffle=True,drop_last=True,batch_size=batchNumber)


In [18]:
def createModal():

    class Net(nn.Module) :
        def __init__(self):
            super().__init__()
            self.input=nn.Linear(2,16)
            self.hidden=nn.Linear(16,16)
            self.output=nn.Linear(16,1)
        def forward(self,x):
            x=F.relu(self.input(x))
            x=F.relu(self.hidden(x))
            return self.output(x)
    net=Net()
    lossFunction=nn.MSELoss()
    optimizer=torch.optim.Adam(net.parameters(),lr=.001)
    return net,lossFunction,optimizer


In [27]:
def TrainModal():
    numEpochs=100
    net,lossFunction,optimizer=createModal()
    losses=[]

    for i in range(numEpochs):
        batchLoss=[]
        batchAcc=[]
        for X,y in train_loader:
            yHat=net(X)
      
            loss=lossFunction(yHat,y)
            batchLoss.append(loss.item())

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        
    with torch.no_grad():
        yHat=net(data)
        acc=100*torch.mean((np.abs(yHat-labels)<1).float())
    with torch.no_grad():
        # test using newly generated numbers and the sum 
        newDataTest=torch.randint(-10,11,size=(N,2)).float()
        newLabelsTest=torch.sum(newDataTest,dim=1,keepdim=True)
        yHat=net(newDataTest)
        testAcc=100*torch.mean((np.abs(yHat-newLabelsTest)<1).float())
    

    return losses,acc,testAcc,net

        
losses,acc,testAcc,net=TrainModal()
print(acc)
print(testAcc)

tensor(100.)
tensor(100.)


In [21]:
import time
for i in range(10):
    currentTime=time.process_time()
    _,acc,testAcc,_2=TrainModal()
    # i used _ because i won't be using the losses
    print(f'#{i} the train acc is {acc} and test acc is {testAcc} it took {time.process_time()-currentTime} to complete')


#0 the train acc is 100.0 and test acc is 100.0 it took 146.01827689899994 to complete
#1 the train acc is 100.0 and test acc is 100.0 it took 144.24295877600002 to complete
#2 the train acc is 100.0 and test acc is 100.0 it took 148.17667183699996 to complete
#3 the train acc is 100.0 and test acc is 100.0 it took 161.59789799700002 to complete
#4 the train acc is 100.0 and test acc is 100.0 it took 145.27511830799995 to complete
#5 the train acc is 100.0 and test acc is 100.0 it took 146.0603996499999 to complete
#6 the train acc is 100.0 and test acc is 100.0 it took 150.60515977599994 to complete
#7 the train acc is 100.0 and test acc is 100.0 it took 141.30256485899986 to complete
#8 the train acc is 100.0 and test acc is 100.0 it took 145.19126052600018 to complete
#9 the train acc is 100.0 and test acc is 100.0 it took 145.77639754600023 to complete


In [32]:
losses,acc,testAcc,net=TrainModal()

yHat=net(data)
for i in range(len(labels)):
    
    print(f'{yHat[i].item()},{labels[i].item()}')

0.001203969120979309,0.0
11.99803352355957,12.0
9.998563766479492,10.0
17.997209548950195,18.0
-7.9991021156311035,-8.0
-10.998146057128906,-11.0
1.0000683069229126,1.0
1.0019984245300293,1.0
11.998198509216309,12.0
-16.99808120727539,-17.0
5.999075412750244,6.0
-7.999255657196045,-8.0
-13.998266220092773,-14.0
2.0001060962677,2.0
11.998361587524414,12.0
-2.9982306957244873,-3.0
-2.997065544128418,-3.0
3.000943660736084,3.0
-0.9984641671180725,-1.0
-8.999397277832031,-9.0
-5.997105121612549,-6.0
1.9993752241134644,2.0
0.002035662531852722,0.0
5.999459743499756,6.0
1.0013501644134521,1.0
-3.999628782272339,-4.0
-8.000703811645508,-8.0
2.000431537628174,2.0
4.999596118927002,5.0
-6.997063159942627,-7.0
17.997264862060547,18.0
9.998235702514648,10.0
3.00003981590271,3.0
-4.999441623687744,-5.0
1.0019984245300293,1.0
3.000243902206421,3.0
1.0009490251541138,1.0
1.0003986358642578,1.0
-9.998310089111328,-10.0
1.0007288455963135,1.0
3.9982240200042725,4.0
5.999075412750244,6.0
-6.99989175796